tasks:
  - type: calculate_similarity
    from:
      files:
        - input/name.txt
      pairs: all
      headers: true
      numbered: true
    options:
      jcn: true
      lch: true
      path: false
    output:
      format: H5
      file_name: output/name.h5
      ds_name: mi
options:
  cores: 19